# Generated by Django 5.0.1 on 2024-01-23 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(default='N/A', max_length=255)),
                ('co', models.CharField(default='N/A', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=255)),
                ('address', models.CharField(default='N/A', max_length=255)),
                ('description', models.TextField(max_length=1080)),
                ('employer_mamad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='JobsApp.employer')),
            ],
        ),
        migrations.CreateModel(
            name='JobsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobsApp.jobs')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
