# Generated by Django 5.0.1 on 2024-01-21 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
