# Generated by Django 5.0.1 on 2024-01-24 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobsApp', '0002_rename_employer_mamad_jobs_employer'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerEntity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cat', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='employer',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='JobsApp.employerentity'),
        ),
    ]
