# Generated by Django 5.0.1 on 2024-01-22 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobsApp', '0002_alter_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
