# Generated by Django 5.0.1 on 2024-01-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobsApp', '0005_jobsuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='address',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
